GET http://localhost:3000/companies

###
GET http://localhost:3000/companies/1

###
POST http://localhost:3000/companies
Content-Type: application/json

{
 "name": "Imobiliária pria",
 "description": "Descrição da imobiliária"
}